### PR TITLE
drop ice 3.5 (Was Ice 37)

### PR DESCRIPTION
**Pull request by jburel**
Add support for Ice 3.7 and remove 3.5

### CODE REVIEW

**Comment by joshmoore** [comment]
Propose 3.0 as a breaking change?

**Comment by joshmoore** [comment]
Otherwise, this looks like it's doing what it should:

```
    TASK [ansible-role-ice : zeroc ice | pip install packages] *********************
    changed: [ice-37]
    changed: [ice-36]
```

(I assume `--diff` or perhaps `-vvv` would show the URLs in question)

**Comment by sbesson** [comment]
Overall makes sense. Same question as https://github.com/openmicroscopy/ansible-role-ice/pull/9#issuecomment-447350090, do we want to break the role semantics by remove Ice 3.5 and updating the default and release as `3.0.0` or add support for new versions as in https://github.com/openmicroscopy/ansible-role-postgresql/pull/14, deprecate the old version and release as e.g. `2.2.0`?

**Comment by manics** [comment]
If we're aiming for a breaking change now would be a good time to add Ubuntu 18.04 support, and also check whether the minimum version of Ansible in `meta/main.yml` is still correct after all changes.

**Comment by jburel** [comment]
I understood from comment on https://github.com/openmicroscopy/ansible-role-ice/pull/8 that we wanted to swap 3.5 by 3.7 
Happy to re-open 3.5 drop first then rework on that one

**Comment by manics** [comment]
If it's easier just add 3.7 (keep 3.5) so it's non-breaking?

**Comment by sbesson** [comment]
I don't particularly mind either way. The general question is whether these roles should remain tailored to our OMERO usage (and match the [latest requirements](http://docs.openmicroscopy.org/omero/5.5.0-m2/sysadmins/version-requirements.html)) or whether we aim at maintaining a wider support.

To be complete, https://github.com/openmicroscopy/ansible-role-ice/pull/9#issuecomment-448166857 was inspired by the following question while simultaneously reviewing https://github.com/openmicroscopy/ansible-role-postgresql/pull/14/: if we are dropping Ice 3.5 and making Ice 3.6 the default in this role, should  the postgresql role do the same and drop Postgresql 9.4 and make Postgresql 9.5/9.6 as the default?

**Comment by manics** [comment]
> The general question is whether these roles should remain tailored to our OMERO usage

Yes, we've got limited resources so I don't think we should support everything, though I think its reasonable to avoid unnecessary breaking changes, especially where the changes required by the user are straight forward, not least because it reduces the work involved with our internal upgrades.

On that basis I'd say:
- it's fine to make the breaking change to the default Ice version and also to drop 3.5, though that doesn't have to be done in this PR
- It's fine to change the default PostgreSQL to 9.6 or 10 which counts as a breaking change, but I'd like input from others on whether we should also remove 9.4 and 9.5 if OMERO will continue to support them, since a major PostgreSQL server upgrade is not automatic.

**Comment by jburel** [comment]
9.5 is the version installed on Ubuntu1604 by the package manager so I don't think we can drop it.

**Comment by manics** [comment]
I meant drop from this role, not necessarily from OMERO

**Comment by jburel** [comment]
This PR has been hijacked, by Pg discussion :-)

**Comment by jburel** [comment]
A rule could be that the minimum version is "dictated" by the version installed by the package manager of the platforms we support
and that across the various repositories. 
As an example, for pg that will be 9.5

**Comment by sbesson** [comment]
I did not intend to create unecessary noise but I was unclear about the roadmap for all these roles. As per above, the three options are:

- `openmicroscopy.ice 3.0.0` with Ice 3.6/3.7 support
- `openmicroscopy.ice 3.0.0` with Ice 3.6/3.7 support and Ubuntu 18.04 support
- `openmicroscopy.ice 2.2.0` with Ice 3.5/3.6/3.7 support

If we are all okay with `3.0.0` but feel we could use more time to investigate the second option (as per https://github.com/openmicroscopy/ansible-role-ice/pull/9#issuecomment-448177503), we can certainyl merge this and even release as as `3.0.0a1` as we have done elsewhere.

**Comment by jburel** [comment]
There is no rush to merge or tag.
This is part of the "infra" prep

**Comment by jburel** [comment]
I have removed ice 3.7 support since we are not planning to continue the "ice" route

**Comment by joshmoore** [comment]
This looks straight-forward. :+1: In the future if we are definitely sure that it will only ever by 3.6, then we could drop the ice_version variable completely.

**Pull request merged**
