### PR TITLE
Update rockylinux9 ubuntu2204

### PR DESCRIPTION
**Pull request by khaledk2**
This PR contains the required modification to update the ice role to work with Rocky Linux 9 and Ubuntu 22.04.
It uses the ice distributions for both of them from `Glencoe`, i.e. 
https://github.com/glencoesoftware/zeroc-ice-ubuntu2204-x86_64 
https://github.com/glencoesoftware/zeroc-ice-rhel9-x86_64

It has been passed on:
https://github.com/khaledk2/ansible-role-ice/actions/runs/6407596865

cc @sbesson @pwalczysko @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
When the role from this PR is added to requirements.yml of the [PR in ansible-role-omero-server](https://github.com/ome/ansible-role-omero-server/pull/69), then the Rockylinux9 test passes, see https://github.com/pwalczysko/ansible-role-omero-server/actions/runs/6408471473/job/17397537578. I am still struggling with the idempotence test on Ubuntu 22.04 in https://github.com/pwalczysko/ansible-role-omero-server/actions/runs/6408471473/job/17397537578 - but this is improbable to be caused by this role, indeed, the server has been installed successfully in the ``converge`` step imho on both platforms. cc @sbesson

**Comment by khaledk2** [comment]
The support for RHEL 9 has been added to this PR;  it supports both Rocky 9 and Red Hat 9.
It has passed on  https://github.com/khaledk2/ansible-role-ice/actions/runs/6422406939
This has tested Rocky Linux 9,  @pwalczysko could you test from your end for Redhat?

**Comment by jburel** [comment]
the ``Ice-xxx-tar.gz`` should be removed from ``/opt`` after unzipping so it might be preferable to download in ``/tmp,`` untar and move to ``/opt``

**Comment by pwalczysko** [comment]
> This has tested Rocky Linux 9, @pwalczysko could you test from your end for Redhat?

This has been tested and test passes.

**Pull request merged**
